### ISSUE TITLE
SALT indexing: facet parity

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/sul-exhibits-template#38]
Facet Parity issues:

Facets present but perhaps not equal:
  - [x] Author:  prob ok - is this only "as creator/contributor?"
  - [x] Organization:   prob ok - is this only "as creator/contributor"?
  - [ ] Year / Date:  (see #49)
  - [ ] Document Type:   (see #48 )

Facets not avail via current spotlight:
  - [ ] Tagged by Donor (see #50) - MODS element:  note displayLabel="Donor tags";  needs to be single valued but repeated MODS field; @peetucket will change template for un-ingested item
  - [ ]  possible broader usage; single string in location/physicalLocation @ndushay will talk to Laura for more examples:
    - [ ] Series  (see #51)
    - [ ] Box  (see #51)
    - [ ] Folder  (see #51)

- [ ] Subseries:  this appears to be a different animal.  (see #52)

spotlight facets to suppress?
  - [ ] Topic  (same 3 topics for all items - actually, there are other topics, too ...)
  - [x] Resource Type (this is searchworks resource type)

![facets](https://cloud.githubusercontent.com/assets/96775/10443058/d557f04a-710d-11e5-8765-d62a68a1b017.png)

Note:  facets are displayed when looking at a single document in saltworks:  we do not intend to continue this behavior in spotlight.

**Comment by ndushay** [comment]
Next step:  identify where to find the info for parity mismatches.

**Comment by peetucket** [comment]
Start with facets that are already there: 

Author - should be ok, comes from <name type="personal" usage="primary"><namePart>XXX</mnamePart></name>.   The flipping of name from first last to last,first is due to updating/normalization of metadata we did after exporting from saltworks.

Organization - should be ok, comes from <name type="corporate"><namePart>XXX</namePart>
</name> node.  Differences again due to metadata normalization after export from saltworks.

Resource Type - fine, and let's leave the new facet name (it used to be Document Type) for now since we have new types like video/audio to deal with.  Not sure where it comes from in MODs or why the values are different, but I think it is ok.

Year - fine, just rename facet from "Date" to "Year" as a curator.  comes from <dateCreated>XXX</dateCreated>

**Comment by ndushay** [comment]
so Resource Type is searchworks specific, and is NOT document type like salt wants.  they want "genre"

**Comment by ndushay** [comment]
Best case for DLSS:   new SALT won't require any facets for data not avail via DOR MODS (i.e.  person, city, corporate entity, company).

**Comment by peetucket** [comment]
Per Scott's email to Peter on October 15, 2015 (copied below), we do not need to worry about the Person, Corporate Entity, City and Company facets.

Hi Peter,

Those facets ("Person", "City", "Corporate Entity", "Company") were derived algorithmically based a small subset of the data, it was only based on about 4000 of the 16000 records.  It was intended as an experiment, both in the auto-tagging process, and in the Saltworks GUI.  In the end we did not think they were performing very well, as there were lots of near duplicates that needed to be merged, and it did not seem to accomplish much more than a full text search would.  So it was never Ed's thinking that these facets would be ported over to the real archive.  They can be dropped.  The only meaningful keywords are the so-called donor keywords (which may be referred to as "tags" in the spreadsheet).

thanks,
Scott

**Comment by ndushay** [comment]
@peetucket  I think I have created issues for all the remaining open issues, except:  I think there may be some topic information that is avail in the new beyond just the three values that are always present.  You may still want to suppress topic as a facet in the spotlight version, but I wanted to make you aware.

If you agree that we've captured all the outstanding facet parity information in the other tickets (linked above), please close this one.
